# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
    - master
    - release/*
  pull_request:
    branches: 
    - master

jobs:
  my-job:
    name: Install dependencies and run tests.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Decrypt secrets.
      run: ./.github/scripts/decrypt_secret.sh
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
      run: npm ci
      run: npm test
      env:
        CI: true
        SPREADSHEET_ID: 1_Wah-_jNWevQMYtXKCv9Zog3isPT2xzxzdkgm-0qLUo 
